# Generated by Django 4.1.13 on 2026-05-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestApp', '0003_customer_location'),
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerApp.order')),
            ],
        ),
    ]
