# Generated by Django 4.1.13 on 2026-05-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_deliveryboy_loginid'),
        ('customerApp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.product'),
            preserve_default=False,
        ),
    ]
