# Generated by Django 6.0.5 on 2026-05-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('guestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='loginId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.logindetails'),
        ),
        migrations.AddField(
            model_name='location',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.district'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminApp.category'),
        ),
    ]
