# Generated by Django 4.1.13 on 2026-05-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('guestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='loginId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.logindetails'),
        ),
    ]
