# Generated by Django 4.1.13 on 2026-05-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestApp', '0003_customer_location'),
        ('adminApp', '0004_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='loginId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guestApp.logindetails'),
            preserve_default=False,
        ),
    ]
