# Generated by Django 4.1.13 on 2026-05-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
