# Generated by Django 4.1.13 on 2026-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestApp', '0002_remove_customer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
